#! /bin/bash

#1.2.2
apt-key list
read
apt-cache policy


grep AllowUnauthenticated /etc/apt/apt.conf.d/*
read

grep -i remove-unused /etc/apt/apt.conf.d/50unattended-upgrades
#Unattended-Upgrade::Remove-Unused-Dependencies "true";
#Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

#bootloaderpass
grub-mkpasswd-pbkdf2
#1.3.1

#1.4
journalctl | grep 'protection: active'










